[project]
name = "project-08-create-a-python-streamlit-bmi-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "panda>=0.3.1",
    "streamlit>=1.44.1",
]
